#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('VULKAN', True)

def build(bld):
	libs = ['mathlib', 'tier1']

	includes = []

	source = [
		"shaderdevicemgrvk.cpp",
        "indexbuffervk.cpp",
        "vertexbuffervk.cpp",
        "hardwareconfig.cpp",
        "shaderapivk.cpp",
        "shaderdevicevk.cpp",
        "shadermanagervk.cpp",
        "shadershadowvk.cpp",
        "viewportvk.cpp",
        "meshmgrvk.cpp",
        "meshvk.cpp",
        "vulkanimpl.cpp"
	]

	bld.shlib(
		source   = source,
		target   = 'shaderapivk',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
