#! /usr/bin/env python3

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = ['appframework']

	source = [
                "main.cpp",
                "hammer_launcher.rc"
	]
}
