#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = ['../public']

	source = [
		'OpenSSLWraper.cpp',
		'SocketLip.cpp',
		'SslSocket.cpp',
        'StdSocket.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'socketlib',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
